-- AlterTable
ALTER TABLE "Client" ADD COLUMN     "attendanceRate" DOUBLE PRECISION,
ADD COLUMN     "isVip" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastVisit" TIMESTAMP(3),
ADD COLUMN     "preferences" JSONB DEFAULT '{}',
ADD COLUMN     "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalVisits" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "availableDays" INTEGER[] DEFAULT ARRAY[0, 1, 2, 3, 4, 5, 6]::INTEGER[],
ADD COLUMN     "availableTimeEnd" INTEGER NOT NULL DEFAULT 17,
ADD COLUMN     "availableTimeStart" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN     "bookingCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isAvailable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "revenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
